005 gettext extraction
catalpainternational/simple-gettext pull request #6
Opened 2019-01-03 02:22 UTC by aersida

Closes #5 

This cleans up the functionality of the gettext_extraction script so that it can be used by projects that include simple-gettext.

### Testing

Please read the updated instructions in the readme on usage - and follow them.

Note that gettext_extraction is NOT meant to do everything for the developer.  Instead it does the heavy lifting of finding all usages of gettext, and determining if any are missing.

2019-01-04 10:17 UTC, raphaelmerx requested changes
I tried removing one of the translations from `extendGettext.js` in hamutuk_mobile, then calling `node node_modules/simple-gettext/scripts/gettext_extraction.js`, and the gettext_extraction.js script didn't add back the missing translation.

Also, this script should not add a new line to `extendGettext.js` every time it's run.

2019-01-04 10:19 UTC, raphaelmerx commented on scripts/gettext_extraction.js
> +const allGettextDeclarations = promiseAny(gettextSourceFiles.map(gettextSourceFile => {
why use promiseAny here, and not Promise.all? We want to wait until all gettext declaration files are read.

2019-01-10 02:59 UTC, md8n commented on scripts/gettext_extraction.js
> +const allGettextDeclarations = promiseAny(gettextSourceFiles.map(gettextSourceFile => {
We 'should' only be finding a single file, either gettext.js or extendGettext.js, but not both (or multiple extendGettext.js) so we want the first resolving promise to go ahead.
I could add an extra test before this, to check whether gettextSourceFiles.length > 1

2019-01-10 04:49 UTC, md8n commented on scripts/gettext_extraction.js
> +const allGettextDeclarations = promiseAny(gettextSourceFiles.map(gettextSourceFile => {
Correction - it should read both gettext.js and a single extendGettext.js - so I'll change

2019-01-10 06:13 UTC, md8n commented
The extra blank line at the end issue has been fixed - it will now remove all extra blank lines except for one (as per eslint requirements)
It reads both gettext.js and extendGettext.js, and writes whatever is missing to the top of extendGettext.js
It does not rewrite extendGettext.js if there is nothing missing.

2019-01-10 08:27 UTC, raphaelmerx commented
Checked that missing translations are added back, and that the new lines are gone.

However, when run in hamutuk_mobile, the script adds `'all day': undefined` in `extendGettext.js`, even though that translation is already present in `node_modules/hamutuk-calendar/src/js/extendGettext.js`. Maybe we should include that file in the `extendGettextSourceFiles` glob?

2019-01-10 08:38 UTC, md8n commented
Good point

Sent from Mail for Windows 10

From: Raphaël Merx
Sent: Thursday, 10 January 2019 17:28 PM
To: catalpainternational/simple-gettext
Cc: md8n; Assign
Subject: Re: [catalpainternational/simple-gettext] 005 gettext extraction (#6)

Checked that missing translations are added back, and that the new lines are gone.
However, when run in hamutuk_mobile, the script adds 'all day': undefined in extendGettext.js, even though that translation is already present in node_modules/hamutuk-calendar/src/js/extendGettext.js. Maybe we should include that file in the extendGettextSourceFiles glob?
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-01-11 00:02 UTC, md8n commented
Here's a couple of options for including 'other' gettext's, such as the one in Hamutuk-Calendar.
1. Don't merge extendGettext.js in with the rest of the library in the dist folder.  That way searching node_modules/**/extendGettext.js will find all 'other' gettexts as well - I think this option is best (it's basically what you suggested).
2. For a given project, parse its package.json to identify its included libraries and then of course parse each of those libraries looking for the relevant declarations - getting very messy.

2019-01-11 01:40 UTC, md8n commented
I went for option 1. and made the relevant change in hamutuk-calendar.

However, the globbing library I use does not support traversal of symlinked folders, so to test we'll need to actually build hamutuk-calendar and update the package proper

2019-01-11 07:36 UTC, raphaelmerx commented on scripts/gettext_extraction.js
> +const commonGettextSourceFiles = getDirListing(`${cwd}/node_modules/{simple-gettext/,**/extend}gettext.js`);
Searching files in all of `node_modules` makes the whole script take a lot longer, 3s vs 0.1s before. I think we can limit ourselves to only searching in hamutuk-calendar for now: 
```javascript
const commonGettextSourceFiles = getDirListing(`${cwd}/node_modules/{simple-gettext/,hamutuk-calendar/**/extend}gettext.js`);
```

2019-01-11 07:36 UTC, raphaelmerx commented on scripts/gettext_extraction.js
> +    console.log(` - reading file: ${filename.replace(re, '')}`);
While these logs are useful for debugging, I think they should be removed on master so we don't print too much information during `cordova run`

2019-01-11 07:37 UTC, raphaelmerx commented on scripts/gettext_extraction.js
> +        console.log(` - files using gettext: ${filenames.join(' ').replace(re, '')}`);
Same here, this is useful for debugging but too verbose for master.

2019-01-11 07:38 UTC, raphaelmerx reviewed
Couple more comments, but this works functionally!

2019-01-13 23:54 UTC, md8n commented on scripts/gettext_extraction.js
> +    console.log(` - reading file: ${filename.replace(re, '')}`);
I'll add a debug option

2019-01-13 23:54 UTC, md8n commented on scripts/gettext_extraction.js
> +        console.log(` - files using gettext: ${filenames.join(' ').replace(re, '')}`);
Hanesan

2019-01-14 00:45 UTC, md8n commented on scripts/gettext_extraction.js
> +const commonGettextSourceFiles = getDirListing(`${cwd}/node_modules/{simple-gettext/,**/extend}gettext.js`);
I've just tried putting in a specific path (this one):
./node_modules/{simple-gettext/,hamutuk-calendar/dist/extend}gettext.js
and ... it takes the same amount of time as the generic one above.  I've also tried
./node_modules/{simple-gettext/gettext.js,hamutuk-calendar/dist/extendgettext.js}
Which is much more specific - and it takes longer!
So anyway, there's now an option to set the commonGettextPath called -commonGettextPath
Or you can leave that out and you'll get the default.

2019-01-14 01:11 UTC, md8n commented
Ok - so running the script without any options, it will NOT display any diagnostic/debug messages, and it will hunt through all of node_modules for files named extendgettext.js (as well as getting gettext.js from simple-gettext)
Add the -d option and it will display the nice diagnostic/debug messages
Add the -commonGettextPath with a globbed path, and it will use the globbed path to look for gettext.js and extendgettext.js (or whatever you tell it)

2019-01-14 01:12 UTC, md8n commented
In terms of performance it seems to be the {brace} expansion in the globbing library that takes the time and not the traversing through all of node_modules.

2019-01-14 01:16 UTC, md8n commented
This PR benefits from the work done for https://github.com/catalpainternational/hamutuk-calendar/pull/15

2019-01-14 05:07 UTC, raphaelmerx commented on scripts/gettext_extraction.js
> +const commonGettextSourceFiles = getDirListing(`${cwd}/node_modules/{simple-gettext/,**/extend}gettext.js`);
Can you try the glob i mentioned above? It drastically changes the run time for me:
```zsh
# with let commonGettextPath = `${cwd}/node_modules/{simple-gettext/,**/extend}gettext.js`;
(mobile) ~/C/hamutuk_mobile ❯❯❯ time node node_modules/simple-gettext/scripts/gettext_extraction.js                     master ✭ ✱ ◼
node node_modules/simple-gettext/scripts/gettext_extraction.js  2.41s user 0.41s system 100% cpu 2.802 total
# with let commonGettextPath = `${cwd}/node_modules/{simple-gettext/,hamutuk-calendar/**/extend}gettext.js`;
(mobile) ~/C/hamutuk_mobile ❯❯❯ time node node_modules/simple-gettext/scripts/gettext_extraction.js                     master ✭ ✱ ◼
node node_modules/simple-gettext/scripts/gettext_extraction.js  0.12s user 0.03s system 90% cpu 0.166 total
```

2019-01-15 01:20 UTC, md8n commented on scripts/gettext_extraction.js
> +const commonGettextSourceFiles = getDirListing(`${cwd}/node_modules/{simple-gettext/,**/extend}gettext.js`);
Yes, I had tried exactly that glob, and it did not yield those same results for me.
Even so I recommend just setting the commonGettextPath argument as you've done in the calling (consuming) project, in this case that would be hamutuk_mobile

2019-01-16 05:23 UTC, aersida commented
Can you update your review please, thanks

2019-01-18 01:49 UTC, md8n commented
We need this passed and packaged so that hamutuk_mobile can pass its tests - they are now dependent on this

2019-01-18 05:23 UTC, merged